### ISSUE TITLE
Updating the scope of the current user

### ISSUE THREAD

**Issue by NolanChan** [wedeploy/wedeploy-sdk-js#206]
@jonnilundy and I are working on a demo that shows how one can use the `auth` service with a `node.js` service.

One issue I've run into is how to change a user's `supportedScopes`. If you use `auth.getUser(id)`, you won't retrieve the user's `token`, which means you won't be able to call `user.updateUser` on that user. There doesn't seem to be any other way to get the user with their token (except by email and password, which I don't have). 

How would you suggest changing the `supportedScopes` of a user properly?

Thanks!

**Comment by NolanChan** [comment]
Hi @henvic , I don't believe we are updating values on the JWT. Really, all I'm asking for is why we don't retrieve the `token` when we make a call to `.getUser(id)`

**Comment by henvic** [comment]
Oh, I see. So, I think for this the answer would be separation of concerns.
A token and the user data are two totally separated things.
-- 
Henrique Vicente
https://henvic.github.io/
https://github.com/henvic
http://flickr.com/photos/henriquev/

**Comment by eduardolundgren** [comment]
@henvic JWT tokens on WeDeploy contains only relevant information for the token stateless ability, they are email, name, and scopes. Storing data into JWT tokens to mimic sessions are really a bad idea, definitely, we are not doing that on our side.

**Comment by ipeychev** [comment]
@zenorocha Zeno, why did you remove this issue from v4.1.0? Now when you go to [see what changes where added to 4.1.0 release](https://github.com/wedeploy/wedeploy-sdk-js/issues?utf8=%E2%9C%93&q=milestone%3A4.1.0), there is nothing?
