### ISSUE TITLE
User fails to login again right after logout

### ISSUE THREAD

**Issue by djalmaaraujo** [wedeploy/wedeploy-sdk-js#213]
### Are you opening a bug report?
Yes

### Environment

JavaScript SDK version: 4.0.1

Environment:
  Browser: Chrome
  Node: it's static
  ReactNative: No
  React VR: No
  Electron: No

### Steps to Reproduce

1. Have a logged user
2. Call auth.signOut().then(() => { redirect code })
3. Click to login again, boom.

### Expected Behavior
The user can login and logout as many times he wants without trying twice to make it work.

### Actual Behavior
- When the user logout and tries to login again, something goes wrong in the redirect request. But if you try again, it works.

![demo](http://g.recordit.co/cC8wEkRw9b.gif)

### Reproducible Demo

```html
    <script src="https://cdn.wedeploy.com/api/4.0.1/wedeploy.js"></script>
    <script>
      window.WeDeployClient = WeDeploy.auth('https://auth-fichamento.wedeploy.io');
    </script>
```

```js
// Code that I use to login
  _requestLogin() {
    var provider = new WeDeployClient.provider.Google();
    provider.setProviderScope("email");

    WeDeployClient.signInWithRedirect(provider);
  }
```

```js
// Code that I use to logout
  componentWillMount() {
    try {
      Auth.logout().then(() => {
        this.setState({redirect: true})
      })
    } catch (e) {
      console.log(e)
    }
```

**Comment by ipeychev** [comment]
Hey @djalmaaraujo,

[Here](https://app-testll.wedeploy.io/) is an example application with just what is needed to test login and logout using Google as provider. It works fine.

Attaching it here too.
[testll.zip](https://github.com/wedeploy/wedeploy-sdk-js/files/1500997/testll.zip)

**Comment by djalmaaraujo** [comment]
@ipeychev I can't reproduce anymore. https://www.fichamento.online/, looks good. Maybe the new auth 2.0 fixed something.
