### ISSUE TITLE
Provide `watch` results in asc instead of desc order

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/wedeploy-sdk-js#225]
Currently, when performing a watch task, it will provide you with a list of all documents in the collection ordered in descending order by most recently created/modified. I am proposing that we should change this to ascending order.

For example, if I have a simple collection of three documents. If I walk through the process of updating each document, this would be the output of my watch:

<img width="592" alt="screen shot 2017-12-05 at 3 01 43 pm" src="https://user-images.githubusercontent.com/23219848/33635611-7ac01e98-d9cd-11e7-8b9a-3d54e67cd962.png">

Then if I want to update my app upon every new change to my database, I would have to select the very last result from the watch. But I have a problem because I now have to always retrieve every document in my database in order to get the very last one that was updated. What if I had an app with 20,000 documents? 

My thought is that since the `watch` is primarily based on the most recently changed or created documents, we should sort them so that those recently changed documents are at the beginning of the results array.

**Comment by pragmaticivan** [comment]
hey @jonnilundy can you provide the code you're using for that? thanks

**Comment by jonnilundy** [comment]
@pragmaticivan did you want all the source code or just the api methods I used?

**Comment by pragmaticivan** [comment]
Just the part you use to watch a collection, asking just to give more context to the issue, thanks

**Comment by jonnilundy** [comment]
@pragmaticivan For sure! Here it is.

```
// Data Endpoint
var weData = WeDeploy.data('db-realtimetest.wedeploy.io');

// Watch method
function myWatch(){
    weData
        .watch('tasks/')
        .on('changes', function(data) {
            console.log("Watching: ", data);
        })
        .on('fail', function(error) {
            console.log(error);
        });
}

// Update method
function myUpdate(id, name){
    weData
        .update('tasks/'+id, {"name": name});
}

**Comment by ipeychev** [comment]
Hey @jonnilundy,

1. This issue is not related to JS SDK. The order comes from the engine.
2. Is there any specific reason that `changes` is used in this case? AFAIR, the result of `changes` is the list of the all the documents in the collection. Actaully not all the documents, there was a limit, I think it was 10000. This was left to cover the followig scenario: there might be an application, which may want to redraw all the documents in a collection when there is a change (any kind of change).
3. You may consider to use other (better) options. For example, `watch` method provides other more precise events. They are three: `create`, `delete` and  `update`. In your case, you may go with `update` event. Here is how:
```javascript
const data = WeDeploy.data('data-myapp.wedeploy.io');
data
  .watch('movies')
  .on('update', movie => {
    console.log('UPDATE', movie);
  })
  .on('fail', error => {
    console.log('UPDATE FAILED', error);
  });
```
Then, everytime you update some movie, you will receive the modified object only and not all the documents in the collection and you will proceed with it - for example, you will redraw it on the page.

The syntax for the other two events is the same:
```javascript
// notify me when a document is created in the collection
data
  .watch('movies')
  .on('create', movie => {...});

// notify me when a document is deleted from the collection
data
  .watch('movies')
  .on('delete', movie => {...});
```

**Comment by jonnilundy** [comment]
@ipeychev This is very helpful! I had a conversation with Ivan yesterday and he was showing me some of these other events you can watch. Is there any way to watch for more than one event on the same request? Like if I wanted to watch for any `update` or `delete` events? I tried using an array but that didn't seem to work. This was my code. 

```
data
    .watch('tasks/')
    .on(['update', 'create'], function(data) {
        console.log("Watching: ", data);
    })
    .on('fail', function(error) {
        console.log(error);
    });
```

**Comment by ipeychev** [comment]
I don't think you can add these events in an array, but it is not bad to have them separated. After all, in a real application you will follow different way depending on the _action_. For example, if your listener to `update` event is called, you know that you will have to update the `task` on the page. In case of `delete` you will have to remove it. If you had a single listener on all those events, you would have most probably an `if` inside and redirecr the application flow there.
This separation gives cleaner application logic.

**Comment by jonnilundy** [comment]
I see, that makes sense! Thanks for explaining. I am still curious if the `changes` response should be inverted but it is a minor issue because of my new knowledge of these other events.

**Comment by ipeychev** [comment]
Good. I think for the type of applications `change` event was invented the order makes sense, but you may open an issue in `engine` repository for further discussion if inverting is worth.
