### ISSUE TITLE
Add a "unique by" filter

### ISSUE THREAD

**Issue by zenorocha** [wedeploy/wedeploy-sdk-js#227]
I need to do a search on a huge data collection (300k entries) and filter by the unique value of a property.

For example, here's a dataset.

```js
[
	{
		createdAt: 1202898898788,
		metadata: {
			emailAddress: "zeno.rocha@liferay.com",
			commit: "eadc738e",
			branch: "master",
			groupUid: "770h906"
		},
		type: "BUILD_SUCCEEDED",
		projectId: "vacation"
	},
	{
		createdAt: 1502898898778,
		metadata: {
			emailAddress: "someone@gmail.com",
			commit: "eadc738e",
			branch: "master",
			groupUid: "770h906"
		},
		type: "BUILD_FAILED",
		projectId: "blah"
	},
	{
		createdAt: 1202898898788,
		metadata: {
			emailAddress: "zeno.rocha@liferay.com",
			commit: "eadc738e",
			branch: "master",
			groupUid: "770h906"
		},
		type: "BUILD_SUCCEEDED",
		projectId: "vacation"
	},
]
```

Instead of fetching all the entries and filtering on the client-side, I would like to have something like:

```js
WeDeploy
	.data('data-myproject.wedeploy.io')
	.uniqueBy('metadata.emailAddress')
	.get('activities')
```

Similar to [lodash's uniqBy](https://lodash.com/docs/4.17.5#uniqBy). Is that possible?

Thanks!

**Comment by ipeychev** [comment]
You can achieve it now, by using [aggregations](https://wedeploy.com/docs/data/filtering-data/) and namely `terms` aggregation type (it is the default one):

```js
WeDeploy.data('data-myproect.wedeploy.io')
  .aggregate('emailAddresses', 'metadata.emailAddress')
  .get('build')
  .then(result => {
    console.log('Email addresses', result.aggregations.emailAddresses);
  })
  .catch(error => {
    console.log('ERROR', error);
  });
```

This will print the following:

```js
{someone@gmail.com: 1, zeno.rocha@liferay.com: 2}
```
i.e. the email and the number of occurrences in the dataset.

**Comment by zenorocha** [comment]
That works for me. Now we just need https://github.com/wedeploy/engine/issues/892 to be addressed. Thanks @ipeychev!
