### ISSUE TITLE
hasSupportedScopes only returns true if every item in a given array matches

### ISSUE THREAD

**Issue by jaredgorski** [wedeploy/wedeploy-sdk-js#265]
### Environment

JavaScript SDK version: wedeploy-middleware on the Admin appears to use v3.5.0

### Steps to Reproduce

1. use `hasSupportedScopes`, passing an array

### Expected Behavior

There should be optional functionality to return `true` if any item in the given array matches a supported scope

### Actual Behavior

`hasSupportedScopes` only returns true if all items in the given array match supported scopes

### Reproducible Demo

Faced this issue on WeDeploy Admin, troubleshooting with @jonnilundy . This issue has also shown up on Console when trying to validate supportedScopes using `hasSupportedScopes` and finding that it does not have a way of seeing if supported scopes includes one of the items in a given array.

**Comment by jaredgorski** [comment]
@ipeychev I have a Pull Request ready for this issue, if I am able to contribute. Please see my email.

**Comment by ipeychev** [comment]
Thanks, Jared, I added some comments [here](https://github.com/wedeploy/wedeploy-sdk-js/pull/266#issuecomment-433822012).
